UPDATE: modified shell configs to have cleaner Bash syntax
notble changes in this commit include:
- to `.bashrc`, removed `export GPG_TTY`
- to `.bashrc`, added a "profile check"
- to `aliasrc`, massive upgrades to readability and performance
- to `aliasrc`, added a reference to `.config/shell/aliasrc_extra`
- to `profile`, added checks for Neovim and Rust

diff --git a/.config/shell/aliasrc b/.config/shell/aliasrc
--- a/.config/shell/aliasrc
+++ b/.config/shell/aliasrc
@@ -1,11 +1,20 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-#####################################################################
-# ALIASES FOR ALL
-#####################################################################
+# The `command` array will contain any commands that should assume `sudo`
+command=(
+    "cryptsetup"
+    "dmesg"
+    "mount"
+    "poweroff"
+    "reboot"
+    "shutdown"
+    "su"
+    "ufw"
+    "umount"
+    "updatedb"
+)
 
-# Aliases that should be common to all Linux installations
-# Should not require any additional packages
+# Aliases for all distros - should not require additional packages
 alias \
     ccat="highlight --out-format=ansi" \
     cp="cp -iv" \
@@ -21,14 +30,12 @@ alias \
     rm="rm -v" \
     sdn="shutdown -h now"
 
-# Aliases that should be common to all Linux installations
-# May require additional packages
+# Aliases for all distros - may require additional packages
 alias \
     bc="bc -ql" \
     ffmpeg="ffmpeg -hide_banner" \
     g="git" \
     lf="lfub" \
-    magit="nvim -c MagitOnly" \
     rsync="rsync -avuP" \
     tmux="tmux -u" \
     trem="transmission-remote" \
@@ -44,129 +51,112 @@ alias \
     ytv="yt -f \"bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best\"" \
     z="zathura"
 
-# Use neovim for vim if present
-[ -x "$(command -v nvim)" ] \
-    && alias \
+# For systems with an `xinitrc` file
+if [[ -f "$XINITRC" ]]; then
+    alias startx="startx $XINITRC"
+fi
+
+# For systems with an `mbsync` file
+if [[ -f "$MBSYNCRC" ]]; then
+    alias mbsync="mbsync -c $MBSYNCRC"
+fi
+
+# `ls` is different on Alpine Linux
+if ! [[ "$(grep "ID=.*alpine" /etc/os-release)" ]]; then
+    alias ls="ls -lahN --color=auto --group-directories-first"
+else
+    alias ls="ls -lah --color=auto --group-directories-first"
+fi
+
+# If `bat` is `batcat`, swap `batcat` for `bat`
+if [[ "$(command -v batcat)" ]]; then
+    alias bat="batcat"
+fi
+
+# If neovim is installed, swap `vim` for `nvim`
+if [[ "$(command -v nvim)" ]]; then
+    alias \
         vim="nvim" \
         vimdiff="nvim -d"
+fi
 
-# Use variable if file exists
-# May not want this on if not dwm
-[ -f "$XINITRC" ] \
-    && alias startx="startx $XINITRC"
+# If `virsh` is installed
+if [[ "$(command -v virsh)" ]]; then
+    command+=("virsh")
+fi
 
-[ -f "$MBSYNCRC" ] \
-    && alias mbsync="mbsync -c $MBSYNCRC"
+# PACKAGE MANAGERS
+if [[ "$(command -v pacman)" ]]; then
+    alias \
+        p="pacman" \
+        update="pacman -Sy" \
+        upgrade="pacman -Syu"
 
-#####################################################################
-# DISTRO-SPECIFIC ALIASES
-#####################################################################
+    command+=("pacman")
+elif [[ "$(command -v nala)" ]] && [[ "$(command -v apt)" ]]; then
+    alias \
+        apt="nala" \
+        update="nala update" \
+        upgrade="nala upgrade"
 
-# the `command` array will be relevant later
-command=()
+    command+=("nala")
+elif [[ "$(command -v apt)" ]]; then
+    alias \
+        update="apt update" \
+        upgrade="apt upgrade"
 
-# `ls` for Alpine
-grep -q "ID=.*alpine" /etc/os-release \
-    && alias ls="ls -lah --color=auto --group-directories-first"
+    command+=("apt")
+elif [[ "$(command -v apk)" ]]; then
+    alias \
+        update="apk update" \
+        upgrade="apk upgrade"
 
-# `ls` for all others
-alias ls="ls -lahN --color=auto --group-directories-first"
+    command+=("apk")
+elif [[ "$(command -v dnf)" ]]; then
+    alias \
+        update="dnf update" \
+        upgrade="dnf update"
 
-# Debian-based aliases
-(grep -q "ID=.*debian" /etc/os-release || grep -q "ID=.*ubuntu" /etc/os-release) \
-    && {
-        # Use nala for apt if present
-        [ -x "$(command -v nala)" ] && alias apt="nala"
+    command+=("dnf")
+elif [[ "$(command -v nixos-rebuild)" ]]; then
+    command+=("nixos-rebuild")
+fi
 
-        alias \
-            update="apt update" \
-            upgrade="apt upgrade"
+# SERVICE MANAGERS
+if [[ "$(command -v sv)" ]]; then
+    alias shutdown="poweroff"
 
-        command+=(
-            "apt"
-            "nala"
-        )
-    }
+    command+=("sv")
+elif [[ "$(command -v systemctl)" ]]; then
+    command+=("systemctl")
+elif [[ "$(command -v rc-service)" ]]; then
+    command+=(
+        "rc-service"
+        "rc-update"
+        "service"
+    )
+fi
 
-# Arch-based aliases
-(grep -q "ID=.*arch" /etc/os-release || grep -q "ID=.*artix" /etc/os-release) \
-    && {
-        alias \
-            p="pacman" \
-            update="pacman -Sy" \
-            upgrade="pacman -Syu"
-
-        command+=(
-            "pacman"
-            "sv"
-        )
-    }
-
-# RHEL-based aliases
-grep -q "ID=.*rocky" /etc/os-release \
-    && {
-        alias \
-            update="dnf update" \
-            upgrade="dnf update"
-
-        command+=(
-            "dnf"
-        )
-
-        # Rocky 8 systems have older `tmux` packages, so this covers that
-        alias \
-            tmux-config="tmux source-file ~/.config/tmux/tmux.conf" \
-            tmux-kill="tmux kill-session -t" \
-            tmux-new="tmux new-session -c ~/ -ds" \
-            tmux-start="tmux new-session -ds blank -c ~/ && tmux-config && tmux new-session -ds homedir -c ~/ && tmux-kill blank && tmux a -t homedir"
-    }
-
-# Alpine Linux aliases
-grep -q "ID=.*alpine" /etc/os-release \
-    && {
-        alias \
-            update="apk update" \
-            upgrade="apk upgrade"
-
-        command+=(
-            "apk"
-            "rc-service"
-            "rc-update"
-            "service"
-        )
-    }
-
-# NixOS aliases
-grep -q "ID=.*nix" /etc/os-release \
-    && {
-        command+=(
-            "nixos-rebuild"
-        )
-    }
-
-#####################################################################
-# "SUDO ASSUMED"
-#####################################################################
-
-# The default additions to `command`
-command+=(
-    "cryptsetup"
-    "mount"
-    "poweroff"
-    "reboot"
-    "shutdown"
-    "su"
-    "systemctl"
-    "ufw"
-    "umount"
-    "updatedb"
-)
+# Rocky Linux aliases
+# Rocky 8 systems run older versions of `tmux`, so these aliases cover that
+if [[ "$(grep "ID=.*rocky" /etc/os-release)" ]]; then
+    alias \
+        tmux-config="tmux source-file ~/.config/tmux/tmux.conf" \
+        tmux-kill="tmux kill-session -t" \
+        tmux-new="tmux new-session -c ~/ -ds"
+fi
 
 # If user is NOT the root user, alias all commands in the `command` array to `sudo $command`
-[ "$(whoami)" = "root" ] \
-    || for command in "${command[@]}" ; do
-        alias $command="sudo $command"
+if ! [[ "$(whoami)" == "root" ]]; then
+    for c in "${command[@]}" ; do
+        alias $c="sudo $c"
     done
+fi
 
-# Clean up by unsetting command
+# Clean up
 unset command
+
+# Load any additional aliases
+if [[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc_extra" ]]; then
+    source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc_extra"
+fi
